# Generated by Django 2.0.4 on 2019-06-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hataraku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
