# Generated by Django 2.0.4 on 2019-06-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hataraku', '0002_auto_20190611_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='year',
            new_name='age',
        ),
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='career',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='industry',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
