# Generated by Django 2.0.4 on 2019-06-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hataraku', '0004_auto_20190611_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
