# Generated by Django 2.0.4 on 2019-06-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hataraku', '0007_auto_20190611_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='industry',
            new_name='industory',
        ),
    ]
