# Generated by Django 2.0.4 on 2019-06-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hataraku', '0008_auto_20190611_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_on_date',
            field=models.DateField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='created_on_time',
            field=models.TimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
