# Generated by Django 2.0.4 on 2019-06-11 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hataraku', '0009_auto_20190611_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_on_time',
        ),
    ]
