# Generated by Django 2.0.4 on 2019-06-11 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hataraku', '0010_remove_post_created_on_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_on_date',
        ),
    ]
