# Generated by Django 2.0.4 on 2019-06-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hataraku', '0011_remove_post_created_on_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
