# Generated by Django 2.0.4 on 2019-06-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hataraku', '0012_auto_20190612_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
