# Generated by Django 2.0.4 on 2019-06-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hataraku', '0013_auto_20190612_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
