# Generated by Django 2.0.4 on 2019-06-11 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hataraku', '0014_auto_20190612_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_on',
        ),
    ]
