# Generated by Django 2.0.4 on 2019-06-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hataraku', '0015_remove_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.CharField(max_length=50),
        ),
    ]
