# Generated by Django 2.0.4 on 2019-06-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hataraku', '0016_auto_20190612_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='career',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='industory',
            field=models.CharField(max_length=30),
        ),
    ]
